### ISSUE TITLE
iscpy_core and submodule 'dns'

### ISSUE THREAD

**Issue by egberts** [egberts/iscpy#1]
During the port from Python2 to Python3 using `futurize` utitlity (from `future` Python package, I got the following error after build and install:

Assumes python3 selected on Debian (via `update-alternatives` utility):

```bash
git clone https://github.com/egberts/iscpy
cd iscpy
python setup.py build
python setup.py install --user
cd test
~/iscpy$ python named_importer_lib_regtest.py 
```
Result is:
```
Traceback (most recent call last):
  File "named_importer_lib_regtest.py", line 46, in <module>
    import iscpy
  File "/home/steve/.local/lib/python3.5/site-packages/iscpy-1.8-py3.5.egg/iscpy/__init__.py", line 38, in <module>
    from iscpy_core.core import *
ImportError: No module named 'iscpy_core'
```

File in question is:  iscpy/__init.py__
Module in question is: iscpy/iscpy/iscpy_core
Original Python2 statement in question:
```
from iscpy_core.core import *
import iscpy_dns.named_importer_lib as dns
```

New Python3 statement (as `futurize` recommended)
```
from __future__ import absolute_import
from .iscpy_core.core import *
from . import iscpy_dns.named_importer_lib as dns
```

**Comment by egberts** [comment]
Fixed it

**Comment by ali-heidari** [comment]
Hello,
Thank you for building such a great tool.
When I installed using:
`pip3 install iscpy`
It raises this error:
`ModuleNotFoundError: No module named 'iscpy_core'`

**Solution**
Install it using:
`pip3 install git+https://github.com/egberts/iscpy.git`

Can you please, update pypi.
Again many thanks
